### ISSUE TITLE
adriconf expects i915_dri.so while i965_dri.so present

### ISSUE THREAD

**Issue by Ristovski** [jlHertel/adriconf#61]
Seems like another corner-case - either `i915_dri.so` or `i965_dri.so` might be present based on the hardware. The kernel driver on the other hand will always be named `i915`.

I have tested symlinking `i915_dri.so` to `i965_dri.so` and can confirm this fixes the issue.

**Comment by jlHertel** [comment]
The issue here is that we load the kernel driver name provided by libdrm, and they sometimes don't match what is in user-space.
This is something I'm actively working on to fix.
The fix here would be to load the data from userspace using egl calls. I still have to figure out how to do this properly.

Blocked by: https://bugs.freedesktop.org/show_bug.cgi?id=111529

**Comment by jlHertel** [comment]
A note on this issue: Mesa 19.2 has been released some days ago and contains the necessary fix for us to able to properly enumerate/name the devices. We still need to wait until this newer version is more widely available before providing a permanent fix.

**Comment by jlHertel** [comment]
Two months have passed since the release of mesa with the necessary fix.
Now is time to choose if we switch to the new version or wait a bit more for distros to catch-up: https://mastodon.technology/@jlhertel/103248363343162917
