### ISSUE TITLE
Non flatpak way to use

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [jlHertel/adriconf#72]
Flatpak have a lot of issues such huge dependencies duplication of files... is not the focus. You removed support for building debs [on this commit](https://github.com/jlHertel/adriconf/commit/a858de74eacc92e4746443d840e515776a605d9a#diff-58231b16fdee45a03a4ee3cf94a9f2c3) why exactly? Both ways to distribute application can coexist

**Comment by jlHertel** [comment]
The Debian package during build-time was more an experiment than actually something I intend to have.
Every distribution has it's own package system and way of publishing software. Implementing all of them is a huge effort, specially given the time constraints I have.

This becomes more complicated when we put the dependencies together. Since we depend on mesa to be very up-to-date, it's hard to support a distro that doesn't regularly update its packages.
Eg: Right now we are allowing any mesa version for the X11 support. 
Mesa >= 19.0 is required for proper Wayland support.
Due to a combined bug in the way we enumerate drivers, as well as how mesa loads drivers under GBM, some drivers don't load and adriconf simply crashes. We will fix this soon, but this will require Mesa >= 19.1.4 (released on 7 August, 2019).

Flatpak is a way we found to provide a package that will work everywhere, has all the latest dependencies and is easy to maintain.


Of course if an issue appears with own-compiled packages or distribution provided packages I'm more than happy to look at them.

**Comment by jlHertel** [comment]
Since no further comment has been made here, I will close this issue.
Feel free to open a new one if you have further questions.
